repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: ["pydantic>=2.0","types-tqdm"]

  # Optional but useful: quick test run before commit
  - repo: local
    hooks:
      - id: pytest
        name: pytest (pre-push)
        entry: C:/BU_SUPERAGENT/.venv/Scripts/python.exe
        language: system
        stages: [push]
        pass_filenames: false
        args: ["-m", "pytest", "-q", "--maxfail=1", "--no-cov"]
