repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: ["pydantic>=2.0","types-tqdm"]

  # Optional but useful: quick test run before commit
  - repo: local
    hooks:
      # Fast unit subset on commit: exclude potentially slow/integration tests
      - id: pytest-fast
        name: pytest (fast)
        entry: C:/BU_SUPERAGENT/.venv/Scripts/python.exe
        language: system
        stages: [commit]
        pass_filenames: false
        timeout: 120
        args: ["-m", "pytest", "-q", "--maxfail=1", "--no-cov", "-m", "not slow"]

      # Full suite on push
      - id: pytest
        name: pytest (full)
        entry: C:/BU_SUPERAGENT/.venv/Scripts/python.exe
        language: system
        stages: [push]
        pass_filenames: false
        timeout: 600
        args: ["-m", "pytest", "-q", "--maxfail=1", "--no-cov"]
